version: '3'

services:
  python-cuda12.2.2-cudnn8:
    image: python-cuda12.2.2-cudnn8
    build:
      context: .
      target: development-base
      shm_size: '4gb'
    working_dir: '/workspace'
    stdin_open: true
    tty: true
    volumes:
      - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
